
image: docker/compose:1.29.2
services:
  - docker:dind
stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - docker-compose build
    - echo "Compile complete."
    - docker-compose --project-name hola_mundo build php
    - docker-compose --project-name hola_mundo build nginx
    - docker-compose --project-name hola_mundo build postgres
    - docker-compose --project-name hola_mundo up -d
    - docker ps
    - sleep 20
    - export BUILD_NUMBER=$CI_PIPELINE_ID
    - docker ps
    - docker exec hola_mundo_php_1 php artisan migrate:fresh --seed --env=gitlab
    - docker exec -t hola_mundo_php_1 php artisan test --env=gitlab --colors=never
    - echo "testing OK!"
    - docker-compose stop
    - docker tag hola_mundo_nginx:latest  mpf-reg.jus.mendoza.gov.ar:9999/amalia/hola_mundo_nginx:GL-$BUILD_NUMBER
    - docker push  mpf-reg.jus.mendoza.gov.ar:9999/amalia/hola_mundo_nginx:GL-$BUILD_NUMBER

    - docker tag hola_mundo_php:latest  mpf-reg.jus.mendoza.gov.ar:9999/amalia/hola_mundo_php:GL-$BUILD_NUMBER
    - docker push  mpf-reg.jus.mendoza.gov.ar:9999/amalia/hola_mundo_php:GL-$BUILD_NUMBER

    - docker tag hola_mundo_postgres:latest  mpf-reg.jus.mendoza.gov.ar:9999/amalia/hola_mundo_postgres:GL-$BUILD_NUMBER
    - docker push  mpf-reg.jus.mendoza.gov.ar:9999/amalia/hola_mundo_postgres:GL-$BUILD_NUMBER
    - docker-compose down
trigger_ahsoka:
  stage: deploy
  variables:
    CI_DEBUG_TRACE: "true"
    CURRENT_VERSION: $CI_PIPELINE_ID
    DEPLOY: hola_mundo
  trigger:
    project: devops/ahsoka

trigger_amalia:
  stage: deploy
  variables:
    CI_DEBUG_TRACE: "true"
    CURRENT_VERSION: $CI_PIPELINE_ID
    DEPLOY: hola_mundo
  trigger:
    project: devops/amalia
